import logo from "$lib/images/iPhone.svg";
import logo1 from "$lib/images/Samsung Galaxy S23 Enterprise ED.svg";
import logo2 from "$lib/images/Samsung Galaxy S23.svg";
import logo3 from "$lib/images/iPhone 14 Pro Max.svg";
import logo4 from "$lib/images/Samsung Galaxy S23 Ultra.svg";
import logo5 from "$lib/images/GoodAsNew.svg";

export const phoneDetails = [
  {
    id: "1",
    name: "SAMSUNG GALAXY S23",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$45.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "$53.00",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo2,
    banner_text: "New",
  },
  {
    id: "2",
    name: "SAMSUNG GALAXY S23 Enterprise ED",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$45.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "$53.00",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo1,
    banner_text: "SAVE £150",
  },
  {
    id: "3",
    name: "SAMSUNG GALAXY S23+",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$57.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo2,
    banner_text: "SAVE £150",
  },
  {
    id: "4",
    name: "SAMSUNG GALAXY S23 Ultra",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$65.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo4,
    banner_text: "",
  },
  {
    id: "5",
    name: "iPhone 14 Pro Max",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$59.00",
    oneOff: "$100.00",
    monthlyPriceBeforeSale: "",
    oneOffPriceBeforeSale: "$250.00",
    availability: "In stock",
    image: logo3,
    banner_text: "",
  },
  {
    id: "6",
    name: "iPhone 14 Pro",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$52.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "$56.00",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo3,
    banner_text: "SAVE £329",
  },
  {
    id: "7",
    name: "iPhone 14 Plus",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$61.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo,
    banner_text: "",
  },
  {
    id: "8",
    name: "iPhone 14",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$38.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "$46.00",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo,
    banner_text: "",
  },
  {
    id: "9",
    name: "Samsung Galaxy S22+ -Good As New",
    description:
      "6.1-inch Dynamic AMOLED 2X display. Super durable Gorilla Glass Victus2. Snapdragon 8 Gen 2. 50 MP main camera. IP68 Water and Dust resistance. Supercharged by EE’s 5G network.",
    green: ["black"],
    capacity: "128GB",
    monthly: "$57.00",
    oneOff: "$8.33",
    monthlyPriceBeforeSale: "$61.00",
    oneOffPriceBeforeSale: "",
    availability: "In stock",
    image: logo5,
    banner_text: "",
  },
];
